"""empty message

Revision ID: fb5a266da793
Revises: a1ef572a205b
Create Date: 2024-01-25 11:28:56.847282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5a266da793'
down_revision = 'a1ef572a205b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('salt', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
